### ISSUE TITLE
Version 2.13 does not contain OSGi metadata anymore

### ISSUE THREAD

**Issue by maho7791** [michel-kraemer/bson4jackson#107]
Hi,
I experienced, that version 2.13.0 does not have OSGi Metadata, where 2.12 has.

**Comment by michel-kraemer** [comment]
I'm sorry. I remove the OSGi metadata when I upgraded Gradle to version 7. Gradle doesn't ship with the OSGi plugin anymore and I didn't expect that anyone still uses OSGi 😉  My bad. I fixed this issue and released a new version 2.13.1. Please try again.

**Comment by maho7791** [comment]
It works thank you. 
Since there are lots of OSGi Microservices out there as well as most of JEE Servers (e.g. Glassfish, Websphere, Netweaver) using OSGi under the hood, OSGi is everything, but not dead ;-)
