### ISSUE TITLE
Error when deserialising BSON containing an array as the root element

### ISSUE THREAD

**Issue by mikeduminy** [michel-kraemer/bson4jackson#31]
Details of the error on stackoverflow: http://stackoverflow.com/questions/17320921/deserialise-array-of-bson-objects-as-root-object-in-java

In short I get a **Can not deserialize instance of _x_ out of START_OBJECT token** when using an array as the root element of a document. The equivalent JSON object would look like this:

```
[{"id":....},{"id":....},{"id":....}....]
```

Can this be changed to work on arrays as root elements?

**Comment by zbutfly** [comment]
Is this issue closed? 
~~~java
ObjectMapper bsoner = new ObjectMapper(new BsonFactory());
// from is bson from an array [Object, Integer, Boolean]
JsonNode node = bsoner.readTree(from);
JsonNodeType type = node.getNodeType(); //type should be ARRAY, now it is OBJECT.
~~~
I checked the value of node, it is an object with integer key:
"0" -> item 0 of array
"1" -> item 1 of array
"2" -> item 2 of array

I'm using jackson 2.7.3 and bson4jackson 2.7.0.

I do think the inner implementation of bson4jackson does not follow all jackson standard. Can someone give a tip, just like how should I fix it? 

Thanks for the product.
