### ISSUE TITLE
Infinite loop in de.undercouch.bson4jackson.io.DynamicOutputBuffer.putUTF8(int, String)

### ISSUE THREAD

**Issue by yoann-duval** [michel-kraemer/bson4jackson#35]
Hello,
I'm randomly encountering an infinite loop in de.undercouch.bson4jackson.io.DynamicOutputBuffer.putUTF8(int, String)

I've got a thread that never ends and takes 100% of one thread of the CPU (on the same set of data, the problem doesn't always occur).

Here is the call stack of the thread :

```
application-akka.actor.default-dispatcher-12 [RUNNABLE]
de.undercouch.bson4jackson.io.DynamicOutputBuffer.putUTF8(int, String)
de.undercouch.bson4jackson.io.DynamicOutputBuffer.putUTF8(String)
de.undercouch.bson4jackson.BsonGenerator._writeCString(String) 
de.undercouch.bson4jackson.BsonGenerator._writeString(String)
de.undercouch.bson4jackson.BsonGenerator.writeString(String)
com.fasterxml.jackson.databind.ObjectWriter.writeValue(OutputStream, Object)
org.jongo.marshall.jackson.JacksonEngine.marshall(Object)
org.jongo.Insert.marshallDocument(Object)
org.jongo.Insert.createDBObjectToInsert(Object)
org.jongo.Insert.save(Object)
org.jongo.MongoCollection.save(Object)
models.audits.PageEntityCollection.save(PageEntity)
```

I have noticed that the thread repetitively call to the CharsetEncoder encode() method.
So I think the thread is block in 
    while (in.remaining() > 0) {
        ...
    }

Any ideas where the issue comes from, or how can I debug it ?

**Comment by yfinkelstein** [comment]
The file size is ~320K. Not sure how best to share it with you.

**Comment by yfinkelstein** [comment]
I submitted a PR #79 . Not sure why it the CI fails. I left some comments in the PR. The trigger in our case is a sequence of 3 byte UTF8 chars side by side such that it causes OVERFLOW. The logic in putUTF8 never recovers from this situation because the 4 byte buffer end up having a limit of 1 and after a flip it becomes a 1 byte buffer. If OVERFLOW is by 1 or 2 bytes your code will never allocate additional memory

**Comment by yfinkelstein** [comment]
After removing the second change the CI build passes. I believe replacing rewind() with clear() is an obvious thing. It fixes the infinite loop problem for me. Please publish a new version ASAP. We use your library in prod and it served us well - good job at developing and maintaining this!
