### ISSUE TITLE
Can't serialize Long value

### ISSUE THREAD

**Issue by mrniko** [michel-kraemer/bson4jackson#43]
Please help me with number de/serialization

        ObjectMapper objectMapper = new ObjectMapper(new BsonFactory());
        objectMapper.registerModule(new BsonModule());

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        objectMapper.writeValue(baos, 1L);

        ByteArrayInputStream bais = new ByteArrayInputStream(baos.toByteArray());
        Long v = objectMapper.readValue(bais, Long.class); // exception is here!

I would like to use bson4jackson and be able to de/serialize number and other simple types. Is it possible?

**Comment by michel-kraemer** [comment]
I'm sorry, but bson4jackson can only serialize and deserialize objects (i.e. Maps) or arrays (or Lists, Sets, Collections). It is not possible to deserialize a single value only. According to the BSON spec every document begins with a 32-bit integer denoting the document's length. It is almost impossible to differentiate between this 32-bit integer and the first 32 bits of the long value you're trying to read. :-/

However, if you find a good solution and can provide a pull request I'll be more than happy to merge it.

Cheers,
Michel

**Comment by pdeschen** [comment]
@michel-kraemer  Maybe have a look at Java mongodb driver which features [org.bson parser and all](https://github.com/mongodb/mongo-java-driver/tree/master/bson)
