### ISSUE TITLE
BsonFactory to support copy() call.

### ISSUE THREAD

**Issue by datalorax** [michel-kraemer/bson4jackson#44]
Currently, calls to BsonFactory.copy() throw IllegalStateException as BsonFactory does not override the copy method.

The copy() method is needed to support the owning ObjectMapper.copy() call, which itself is useful to allow mappers to be copied and modified, without affecting the source mapper.

**Comment by datalorax** [comment]
I've cloned and fixed this issue, if you care to let me contribute...?

**Comment by michel-kraemer** [comment]
Thanks. I'll close this issue as it is now tracked in #45

Michel
