### ISSUE TITLE
Support for CharacterEscapes

### ISSUE THREAD

**Issue by tmfset** [michel-kraemer/bson4jackson#46]
I was wondering if there are any plans to support the CharacterEscapes feature introduced in Jackson 1.8?

I'm working on trying to escape the '.'s and '$'s in field names so they can be properly stored in mongo. I took a good long look at the source and although I can set the correct escapes on a JsonGenerator, they will have no effect in the BsonGenerator implementation.

Thanks, let me know what you think!

**Comment by michel-kraemer** [comment]
Sounds great. We can definitely implement this in bson4jackson. Can you provide a short code snippet demonstrating what you want to do and how bson4jackson fails?

Thanks,
Michel

**Comment by tmfset** [comment]
Certainly! Here's an example CharacterEscapes implementation that replaces '.'s with a unicode equivalent:

    class MongoCharacterEscapes extends CharacterEscapes {

        public static MongoCharacterEscapes inst = new MongoCharacterEscapes();
        private MongoCharacterEscapes() {}

        @Override
        public int[] getEscapeCodesForAscii() {
            int[] escapes = CharacterEscapes.standardAsciiEscapesForJSON();
            escapes['.'] = CharacterEscapes.ESCAPE_CUSTOM;
            return escapes;
        }

        @Override
        public SerializableString getEscapeSequence(int ch) {
            switch(ch) {
                case '.': return new SerializedString("\uff0e");
            }
            return null;
        }
    }

Then to test it:

    public static void main(String[] args) throws IOException {
        // Without escapes
        testCharacterEscapes(false, false);
        testCharacterEscapes(true,  false);

        // With escapes
        testCharacterEscapes(false, true);
        testCharacterEscapes(true,  true);
    }

    public static void testCharacterEscapes(boolean useBson, boolean useEscapes) throws IOException {
        // Our test node to be serialized.
        JsonNode node = new ObjectMapper().readTree("{ \"some.field\": \"some.val\" }");

        ObjectMapper mapper = useBson ? new ObjectMapper(new BsonFactory()) :
                                        new ObjectMapper();

        if (useEscapes)
            mapper.getFactory().setCharacterEscapes(MongoCharacterEscapes.inst);

        for (byte b : mapper.writeValueAsBytes(node))
            System.out.printf("%02x ", b);
        
        System.out.println();
    }

This gives the following output (formatted so we can see the content better):

                            s  o  m  e  .          f  i  e  l  d                   s  o  m  e  .          v  a  l
    // Without escapes
    default 7b 22           73 6f 6d 65 2e         66 69 65 6c 64  22 3a 22        73 6f 6d 65 2e         76 61 6c  22 7d 
    bson    1e 00 00 00 02  73 6f 6d 65 2e         66 69 65 6c 64  00 09 00 00 00  73 6f 6d 65 2e         76 61 6c  00 00

    // With escapes
    default 7b 22           73 6f 6d 65 (ef bc 8e) 66 69 65 6c 64  22 3a 22        73 6f 6d 65 (ef bc 8e) 76 61 6c  22 7d 
    bson    1e 00 00 00 02  73 6f 6d 65 2e         66 69 65 6c 64  00 09 00 00 00  73 6f 6d 65 2e         76 61 6c  00 00 

    
So here we can see that the default generator uses the character escapes but the bson generator produces the same output either way.

Now to be honest, I'm not really sure supporting this will solve my actual problem of not being able to store field names with '.'s in mongo. I can't remember if the java driver does the check before or after serializing the data, but I figure this might be a step along the way towards a good solution.

Thanks!
Tom

**Comment by michel-kraemer** [comment]
I've just implemented the feature. I will release a new version of the library later today.

**Comment by tmfset** [comment]
Awesome! Thanks a lot, looking forward to using this :)

**Comment by rchom** [comment]
How do you convert the escaped bson back to the original json?  I would expect this test to pass:

```java
    @Test
    public void characterEscapesAndBack() throws Exception {
        String json = new String("{ \"some.field\": \"some.val\", "
                + "\"another\": \"field\", "
                + "\".some\": \".field\", "
                + "\"some.\": \"field.\" }");
        JsonNode node = new ObjectMapper().readTree(json);

        ObjectMapper bsonMapper = new ObjectMapper(new BsonFactory());
        bsonMapper.getFactory().setCharacterEscapes(new CharacterEscapes() {
            private static final long serialVersionUID = 283833498358662446L;

            @Override
            public int[] getEscapeCodesForAscii() {
                int[] escapes = java.util.Arrays.copyOf(CharacterEscapes.standardAsciiEscapesForJSON(), '\uff0e' + 1);
                escapes['.'] = CharacterEscapes.ESCAPE_CUSTOM;
                escapes['\uff0e'] = CharacterEscapes.ESCAPE_CUSTOM; // '.'
                return escapes;
            }

            @Override
            public SerializableString getEscapeSequence(int ch) {
                switch (ch) {
                    case '.':
                        return new SerializedString("\uff0e");
                    case '\uff0e':
                        return new SerializedString(".");
                }
                return null;
            }
        });

        byte[] bsonBytes = bsonMapper.writeValueAsBytes(node);
        BasicBSONDecoder decoder = new BasicBSONDecoder();
        BSONObject bsonObject = decoder.readObject(bsonBytes);
        String roundtrippedJson = bsonObject.toString();

        assertThat(json, equalTo(roundtrippedJson));
    }
```

**Comment by tmfset** [comment]
I don't think jackson supports unescaping characters, you could try your code with the default object mapper though and see what happens.
