### ISSUE TITLE
Unable to read a BSON document with a MinKey inside

### ISSUE THREAD

**Issue by bguerout** [michel-kraemer/bson4jackson#51]
Since 2.5.0 a BSON document with a MinKey can no longer be read from a StaticBufferedInputStream wrapped by a LittleEndianInputStream.

See pull request #50

**Comment by bguerout** [comment]
Hello, have you found time to check this issue ?

**Comment by michel-kraemer** [comment]
@bguerout I pushed a commit that should fix the issue. Can you please build the library and check if it works for you now?

**Comment by bguerout** [comment]
Ok, it works.
Thanks.
