### ISSUE TITLE
Problem to add Binary Streaming 

### ISSUE THREAD

**Issue by mayras** [michel-kraemer/bson4jackson#54]
you have plenty of methods which can be extended, for example:

JsonToken handleBinary()

but I can't get variable "_in" to get what I would, also class BsonParser.Context isn't available and so on ... can u make it protected that developers can do necessary changes? I want to implement own streaming of big files for BSON, it's really necessary

**Comment by michel-kraemer** [comment]
You're right. Thanks for making me aware of this.
