### ISSUE TITLE
2.7.0 release is missing on Maven Central/JCenter

### ISSUE THREAD

**Issue by mcmil** [michel-kraemer/bson4jackson#58]
Unfortunately 2.7.0 is not available in my builds. I checked Maven Central and JCenter, and the package is missing:

https://bintray.com/bintray/jcenter/de.undercouch%3Abson4jackson/view
http://mvnrepository.com/artifact/de.undercouch/bson4jackson

Also the releases page for version 2.7.0 is linking to the 2.6.0 jar

**Comment by michel-kraemer** [comment]
Ooops. Sorry. And thanks for notifying me so quickly!

It seems I accidentally had overwritten 2.6.0 on Maven central (I didn't even know this was possible). I fixed it by re-uploading 2.6.0 and then I uploaded 2.7.0 (the real one). Now everything should be in order again.

Cheers,
Michel

**Comment by mcmil** [comment]
Thank you for your fast reaction :) I think that JCenter still has the 2.7.0 missing - https://bintray.com/bintray/jcenter/de.undercouch%3Abson4jackson/view#files/de/undercouch/bson4jackson.

**Comment by michel-kraemer** [comment]
@mcmil It usually takes a couple of hours for Bintray to pick up the new version. It's online now.

**Comment by mcmil** [comment]
You are right, I thought it was lost somehow  :) Thanks!
