### ISSUE TITLE
BSON unmarshalling creates a lot of garbage

### ISSUE THREAD

**Issue by sbodese** [michel-kraemer/bson4jackson#75]
Hi, 

actually i figure out that the used underlying BSON unmarshalling creates a lot of garabage (round 540 MB) to unmashalling 4.7 MB of mongoDB objects. It seems that these StaticByteBuffers are unreachable for the JVM escape analysis. 

What can we do pls?

Greetings Steffen

![bildschirmfoto 2017-07-05 um 11 53 34](https://user-images.githubusercontent.com/7249354/27860611-a25fdfa6-617d-11e7-810d-2779ec460fc8.png)

**Comment by michel-kraemer** [comment]
Hi Steffen,

This looks like a memory leak to me. Are you closing all your input streams correctly? Please check that. Also check if you close `BsonParser` properly. Let me know if the problem persists.

Cheers,
Michel

**Comment by sbodese** [comment]
Hi Michael, 
hmm, the whole call path is inside this JacksonDBDecoder which uses your BSONParser. So this seems for me thats this StaticBufferdInputStream will be completely handled in your BSONParser library if you consider this profiler - call tree picture. In my code i dont create any Inputstream for a further usage at your library.

Greetings
Steffen

**Comment by michel-kraemer** [comment]
I checked the code and I couldn't find a reasonable explanation for this. It seems the `BsonParser` is correctly closed by `JacksonDBDecoder`, so all static buffers should be released.

Would it be possible to provide a minimum working example that demonstrates the issue, so I can further investigate it?
