### ISSUE TITLE
Leading 4 bytes are all zeroes

### ISSUE THREAD

**Issue by yfinkelstein** [michel-kraemer/bson4jackson#80]
It appears that in version 2.8 a new bug was introduced that did not exist in 2.7: in some cases the serialized bson does not have a valid length in the first 4 bytes. Here is an example of what we see:
(this is octal/ascii encoding) 

 \000\000\000\000\020int\000YxiA\020intToIncrement\000YxiA\020intToRename\000YxiA\tdate\000
I know that BSON serializer writes the length after the document is fully serialized and its length becomes know. Can it be that under some circumstances that length is not patched into the leading bytes?

Thanks

**Comment by yfinkelstein** [comment]
BsonGenerator.Feature.ENABLE_STREAMING is not enabled...

**Comment by bguerout** [comment]
Hi there,

I'm not sure about that but may be the issue you described is related to a regression we found in jongo when moving from bson4jackson 2.7.x to 2.8.x/2.9.x: https://github.com/bguerout/jongo/issues/322#issuecomment-366502380

**Comment by michel-kraemer** [comment]
Thanks, @bguerout, for the link. Was this a regression in bson4jackson or in Jongo? Is there anything I can do for you?

@yfinkelstein I tried to reproduce the error with no avail. I used the following code:

```java
package de.undercouch.bson4jackson;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.ByteArrayOutputStream;
import java.util.LinkedHashMap;
import java.util.Map;

public class Issue80 {
    public static void main(String[] args) throws Exception {
        Map<String, Object> data = new LinkedHashMap<String, Object>();
        data.put("Int32", 42);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        BsonFactory bsonFactory = new BsonFactory();
        ObjectMapper om = new ObjectMapper(bsonFactory);
        om.registerModule(new BsonModule());
        om.writeValue(baos, data);

        byte[] r = baos.toByteArray();

        for (int i = 0; i < r.length; ++i) {
            String s = Integer.toHexString(r[i]);
            if (s.length() < 2) {
                s = "0" + s;
            }
            System.out.print(s + " ");
        }
        System.out.println();
    }
}
```

It prints:

    10 00 00 00 10 49 6e 74 33 32 00 2a 00 00 00 00 

Just as expected. Can you provide a small reproducer to demonstrate the issue?

**Comment by bguerout** [comment]
When upgrading to bson4jackon 2.8+, lot of integration tests in Jongo failed due to `While decoding a BSON document 4 bytes were required, but only 0 remain` error

I don't think this comes from Jongo because nothing has been modified in this area in v1.4.0 and we were able to reproduce the problem with v1.3.0.

We have fixed this issue by overriding the `flush` method in `BsonGenerator` and rollbacking to the 2.7+ behavior

Unfortunately i haven't dug enough to be able to open an issue with an explanation out of Jongo context.

**Comment by spicyrock** [comment]
@michel-kraemer I am able to reproduce the bug:

`public static void main(String[] args) throws IOException {
    
    	ObjectMapper objectMapper = new ObjectMapper();
    	ObjectNode objectNode = objectMapper.createObjectNode();
    	objectNode.putPOJO("date", new Date());
    	
   
    	ByteArrayOutputStream bos = new ByteArrayOutputStream();
    	
    	ObjectMapper om = new ObjectMapper();
    	BsonFactory bf = new BsonFactory(om);
    	BsonGenerator gen = bf.createGenerator(bos);
    	om.writeTree(gen, objectNode);
    	gen.close();
	    
    	byte[] bin = bos.toByteArray();
    	for (byte b : bin)
    		System.out.print(b + ",");
    	
    }`

Output using 2.7.0 (correct)
19,0,0,0,18,100,97,116,101,0,-35,57,-47,101,99,1,0,0,0,

Output using 2.8.0 (incorrect)
0,0,0,0,18,100,97,116,101,0,13,112,-46,101,99,1,0,0,1,0,0,0,

**Comment by yfinkelstein** [comment]
@michel-kraemer This is the one

**Comment by yfinkelstein** [comment]
Looks like a serious regression. Isn't there a test on Data serialization?

**Comment by michel-kraemer** [comment]
@spicyrock Thanks for the reproducer. I'll have a look at it as soon as I can.

**Comment by michel-kraemer** [comment]
I fixed the bug and uploaded a new snapshot to https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/bson4jackson/

@yfinkelstein @spicyrock Please test the snapshot and check if it resolves your problem. I will then release a new version. Thanks for the support!

@bguerout This should also resolve your issue.

**Comment by bguerout** [comment]
@michel-kraemer I can confirmed that  `2.9.2-SNAPSHOT` fixes the issue found in Jongo.
Overriding the `flush` method in `BsonGenerator` is no longer needed.

Thanks a lot.

**Comment by spicyrock** [comment]
@michel-kraemer  Do you know when you will build 2.9.2-RELEASE?  Thanks

**Comment by michel-kraemer** [comment]
@spicyrock Today 😄

**Comment by michel-kraemer** [comment]
2.9.2 has just been released.

**Comment by spicyrock** [comment]
Thank you @michel-kraemer
