### ISSUE TITLE
BigDecimal precision

### ISSUE THREAD

**Issue by alechenninger** [michel-kraemer/bson4jackson#84]
Looking here: https://github.com/michel-kraemer/bson4jackson/blob/32d2ab3c516b3c07490fdfcf0c5e4ed0a2ee3979/src/main/java/de/undercouch/bson4jackson/BsonGenerator.java#L567

Specifically:

```java
		float f = dec.floatValue();
		if (!Float.isInfinite(f)) {
			writeNumber(f);
		} else {
			double d = dec.doubleValue();
			if (!Double.isInfinite(d)) {
				writeNumber(d);
			} else {
				writeString(dec.toString());
			}
		}
```

Since writeNumber(float) converts to double anyway, why even bother first converting to a float value? If I understand correctly, this looses precision for no reason because either way we write a double value.

I would suggest just removing the first if clause entirely and going straight to double like so: (and can open a PR if this is not flawed);

```java
		if (isEnabled(Feature.WRITE_BIGDECIMALS_AS_STRINGS)) {
			writeString(dec.toString());
			return;
		}

		double d = dec.doubleValue();
		if (!Double.isInfinite(d)) {
			writeNumber(d);
		} else {
			writeString(dec.toString());
		}
```

**Comment by michel-kraemer** [comment]
Thanks for spotting this. I think you're absolutely right. I wonder why nobody has ever complained about this.

A PR would be very welcome. Thanks! You will probably need to adapt the unit tests slightly.
