### ISSUE TITLE
BsonGenerator does not handle null values correctly

### ISSUE THREAD

**Issue by sashavol** [michel-kraemer/bson4jackson#85]
When using BsonGenerator, calls to writeString and writeNumber throw a NullPointerException if the given value is null. 

The correct behavior is to call writeNull(): see jackson-core's [writeString(String)](https://github.com/FasterXML/jackson-core/blob/d9d88ab41c3984f2d978dd616de04e9996530d4d/src/main/java/com/fasterxml/jackson/core/json/UTF8JsonGenerator.java#L473), [writeNumber(BigInteger)](https://github.com/FasterXML/jackson-core/blob/d9d88ab41c3984f2d978dd616de04e9996530d4d/src/main/java/com/fasterxml/jackson/core/json/UTF8JsonGenerator.java#L978), and [writeNumber(BigDecimal)](https://github.com/FasterXML/jackson-core/blob/d9d88ab41c3984f2d978dd616de04e9996530d4d/src/main/java/com/fasterxml/jackson/core/json/UTF8JsonGenerator.java#L1021)

**Comment by michel-kraemer** [comment]
@sashavol Thanks for reporting the issue. I pinned it so it won't be closed by the bot. I will investigate it later.

**Comment by michel-kraemer** [comment]
@sashavol I've investigated the issue and decided to keep the behaviour as it currently is. The reason for this is that BSON does not have a `null` string. It has a special type for `null` values but strings must always be defined (see the specification: http://bsonspec.org/spec.html).

If you have a specific use case where you require this feature, please let me know. I can add a feature flag if necessary.
