### ISSUE TITLE
UnsafeByteArrayInputStream.read for bytes >= 0x80 returns negative integer, caller thinks "Oh, EOF"

### ISSUE THREAD

**Issue by neopaf** [michel-kraemer/bson4jackson#87]
Michel, first let me thank you enourmously for your efforts.
I'm basing my custom binary format on your approach and that saved me tons of investigations.

I've found/fixed small bug you may want to fix back in your code:
## before
```java
    @Override
    public int read() {
        return _pos >= _count ? -1 : _buf[_pos++];
    }
```
Here, when buffer contains byte with sign bit on this code returns negative integer.

CountingInputStream.read caller assumes EOF situation, while there are more bytes available.

Premature EOF causes stops further parsing of input buffer past 0x80 (or higher) byte.

## suggest this
```java
    @Override
    public int read() {
        return _pos >= _count ? -1 : (_buf[_pos++] & 0xFF); // PAF bugfix
    }
```

**Comment by michel-kraemer** [comment]
Thanks. This looks really interesting. Can you provide sample data that causes the issue? If possible, can you also write a unit test that demonstrates the problem so that we can cover against regressions in the future?
