### ISSUE TITLE
Buffer caching for heavy multithreaded load

### ISSUE THREAD

**Issue by neopaf** [michel-kraemer/bson4jackson#89]
Michel, I see that current implementation of 
```java
/**
 * Keeps thread-local re-usable buffers. Each buffer is identified by a key.
 * This class is a singleton, whereas the reference to the instance is held
 * in a {@link SoftReference} so buffers can be freed when they are not needed
 * anymore.
 * @see com.fasterxml.jackson.core.util.BufferRecycler
 * @author Michel Kraemer
 */
public class StaticBuffers {
```

was designed with good intent, but we have only 1 buffer by each key.

For a massive parallel workload this does not work well.

Did you consider adding a bit better buffer caching?

**Comment by michel-kraemer** [comment]
@neopaf Sorry for my late answer. Can you elaborate on that? Maybe you can provide a unit test or a small sample program that demonstrates your requirements. Cheers.

**Comment by neopaf** [comment]
My colleague @iruno discovered that I was wrong when raise this.

Stas, please elaborate, so Michel could close it in peace?

**Comment by iruno** [comment]
Greetings!

We can see StaticBuffers are `thread-local`. So we have 1 buffer by each key per `thread`. As far as I understand it is enough for bson4jackson implementation.

@neopaf In our `ap4jackson` project we have one major difference: we need to have at least two re-usable buffers by each key.
That is why we have implemented different ByteBufferPool.

I think we can close this issue.

**Comment by neopaf** [comment]
@iruno Stas, thanks.

I assume "we need" came from our own specifics.

**Comment by michel-kraemer** [comment]
Thanks for the feedback!
