### ISSUE TITLE
Failed to deserialize object

### ISSUE THREAD

**Issue by liponcio** [michel-kraemer/bson4jackson#91]
First of all, thanks for all the hard work on this amazing project!
I have this problem deserializing an object

Having this:
```
public class Foo implements Serializable {
    private boolean prop1;
    private boolean prop2;

    public Foo() {
        prop1 = false;
        prop2 = false;
    }    

    public boolean hasProp1() {
        return prop1;
    }
    
    public void setProp1(boolean prop1) {
        this.prop1 = prop1;
    }
    
    public boolean isProp2() {
        return prop2;
    }
    
    public void setProp2(boolean prop2) {
        this.prop2 = prop2;
    }
}
```
When I have an object with both prop1 and prop2 with a _true_ value. 
I serialize both, and when I deserialize I get prop 2 at _true_ and prop1 at _false_.

Changing the getter of prop1 from _hasProp1_ to _isProp1_ I can deserialize both with the correct value

Wasn't I supposed to get the object deserialized having whichever name?

**Comment by michel-kraemer** [comment]
This sounds more like a question regarding Jackson to me than bson4jackson. Maybe you have to annotate your getter with `@JsonGetter` or something. I'd recommend to ask your question here: https://github.com/FasterXML/jackson-databind

If this does not help, please come back here again and open a new issue. If possible, provide a unit test, so I can easily reproduce the issue. Thanks.
