### ISSUE TITLE
Support for Jackson 2.12

### ISSUE THREAD

**Issue by hisener** [michel-kraemer/bson4jackson#93]
Hey, is there any plan to support Jackson 2.12?

We found one incompatibility with bson4jackson 2.11 and Jackson 2.12. In https://github.com/FasterXML/jackson-core/issues/631, they introduced `JsonParser#getNumberValueExact` method. I think `BsonParser` should override that method and delegate to `BsonParser#getNumberValue`.

https://github.com/michel-kraemer/bson4jackson/blob/344ea73d509710f8c0082dbec669a6903dc1b412/src/main/java/de/undercouch/bson4jackson/BsonParser.java#L703-L706

**Comment by michel-kraemer** [comment]
Thanks for reporting this!

bson4jackson 2.12.0 has just been released. The issue has been fixed in 36377e86c69c673d0bff6027335101705c878c06.

**Comment by hisener** [comment]
Thank _you_!
